# Generated by Django 3.2.3 on 2021-05-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_comment_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comment_delete',
        ),
    ]
