# Generated by Django 3.2.3 on 2021-05-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_comment_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment_delete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
